"use client"

import React, { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'ru' | 'en' | 'uz'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ru: {
    // Header
    'nav.home': 'Главная',
    'nav.about': 'О хакатоне',
    'nav.program': 'Программа',
    'nav.participants': 'Участники',
    'nav.criteria': 'Критерии',
    'nav.prizes': 'Призы',
    'nav.partners': 'Партнеры',
    'header.participate': 'Участвовать',

    // Hero Content
    'hero.hackathon': 'Хакатон',
    'hero.location_year': 'Ташкент 2025',
    'hero.subtitle': 'Первый Vibe Coding хакатон в Узбекистане',
    'hero.description': '2-дневный интенсивный хакатон для создания стартапов с помощью AI-инструментов',
    'hero.date': '15-16 ноября 2025',
    'hero.location': 'Ташкент, Узбекистан',
    'hero.participants': '150 участников',
    'hero.prize': '$6000 призовой фонд',
    'hero.register': 'Зарегистрироваться',
    'hero.learn_more': 'Узнать больше',

    // Hackathon Details
    'details.what_is_vibe': 'Что такое Vibe Coding?',
    'details.vibe_description': 'Vibe Coding — это революционный подход к разработке, где участники создают функциональные приложения и стартапы, используя AI-инструменты нового поколения.',
    'details.mission': 'Миссия хакатона:',
    'details.mission_text': 'Мы в Angel Connect верим что разработка и подход к созданию IT продуктов это область где прямо сейчас происходят самые глобальные изменения. Миссия нашего VibeCode хакатона это доказать что небольшие команды сосредоточенные на создании продуктов с помощью AI могут достигать фантастических результатов уже сегодня.',
    'details.slogan': 'Будущее уже здесь',

    // About Section
    'about.title': 'О хакатоне',
    'about.subtitle': 'Революция в разработке с AI',
    'about.innovation_title': 'Инновационный формат',
    'about.innovation_text': 'Первый хакатон в регионе, полностью посвященный разработке с использованием AI-инструментов нового поколения',
    'about.community_title': 'Сильное сообщество',
    'about.community_text': '150+ участников из лучших IT-компаний, стартапов и университетов Узбекистана',
    'about.networking_title': 'Премиальный нетворкинг',
    'about.networking_text': 'Уникальная возможность познакомиться с ведущими экспертами, инвесторами и предпринимателями региона',
    'about.prizes_title': 'Серьезные призы',
    'about.prizes_text': '$6000 призовой фонд, менторство от экспертов и возможности для дальнейшего развития проектов',

    // Hackathon Program
    'program.title': 'Программа хакатона',
    'program.subtitle': 'Интенсивный 2-дневный марафон инноваций',
    'program.day1': 'День 1 - Старт и разработка',
    'program.day1_date': 'Суббота, 15 ноября',
    'program.day2': 'День 2 - Финал и презентации',
    'program.day2_date': 'Воскресенье, 16 ноября',
    'program.registration': 'Регистрация',
    'program.opening': 'Торжественное открытие',
    'program.idea_pitches': 'Питчи идей (60 секунд на идею)',
    'program.team_formation': 'Формирование команд',
    'program.lunch': 'Обед',
    'program.development_start': 'Начало разработки',
    'program.workshop': 'Воркшоп "Агентное программирование"',
    'program.mentoring': 'Менторские сессии',
    'program.dinner': 'Ужин',
    'program.evening_workshops': 'Вечерние воркшопы по Vibe Coding инструментам',
    'program.night_dev': 'Ночная разработка (опционально)',
    'program.breakfast': 'Завтрак',
    'program.final_dev': 'Финальная доработка проектов',
    'program.stop_dev': 'Стоп-разработка',
    'program.presentation_prep': 'Подготовка презентаций',
    'program.final_pitches': 'Финальные питчи (3 минуты + 2 минуты Q&A)',
    'program.jury_evaluation': 'Оценка жюри',
    'program.results': 'Объявление результатов и награждение',
    'program.networking_closing': 'Нетворкинг и закрытие',

    // Participants Section
    'participants.title': 'Кто может участвовать',
    'participants.subtitle': 'Хакатон открыт для всех профессионалов, готовых экспериментировать с AI-инструментами',
    'participants.vibe_coders': 'Vibe Coders',
    'participants.vibe_coders_subtitle': 'основная категория',
    'participants.vibe_coders_desc': 'Энтузиасты AI-инструментов',
    'participants.vibe_coders_item1': 'Энтузиасты AI-инструментов',
    'participants.vibe_coders_item2': 'Продукт-менеджеры',
    'participants.vibe_coders_item3': 'Предприниматели с техническим мышлением',
    'participants.vibe_coders_item4': 'Маркетологи, желающие создавать MVP',
    'participants.designers': 'Дизайнеры',
    'participants.designers_subtitle': 'творческие профессионалы',
    'participants.designers_desc': 'UX/UI и продуктовые дизайнеры',
    'participants.designers_item1': 'UX/UI дизайнеры',
    'participants.designers_item2': 'Продуктовые дизайнеры',
    'participants.designers_item3': 'Специалисты по пользовательскому опыту',
    'participants.developers': 'Разработчики',
    'participants.developers_subtitle': 'технические специалисты',
    'participants.developers_desc': 'Frontend, Backend, Mobile, AI/ML',
    'participants.developers_item1': 'Frontend/Backend разработчики',
    'participants.developers_item2': 'Fullstack разработчики',
    'participants.developers_item3': 'Mobile разработчики',
    'participants.developers_item4': 'AI/ML инженеры',
    'participants.business': 'Бизнес-профессионалы',
    'participants.business_subtitle': 'предпринимательское сообщество',
    'participants.business_desc': 'Стартап-основатели и аналитики',
    'participants.business_item1': 'Стартап-основатели',
    'participants.business_item2': 'Бизнес-аналитики',
    'participants.business_item3': 'Венчурные аналитики',
    'participants.business_item4': 'Отраслевые эксперты',
    'participants.requirements_title': 'Требования к участникам',
    'participants.teams_title': 'Команды',
    'participants.projects_title': 'Проекты',
    'participants.team_req1': 'До 3 участников в команде',
    'participants.team_req2': 'Возраст от 16 лет',
    'participants.team_req3': 'Физическое присутствие 2 дня',
    'participants.project_req1': 'Активное использование AI-инструментов',
    'participants.project_req2': 'Разработка с нуля во время хакатона',
    'participants.project_req3': 'Функциональный MVP к концу',
    'participants.req_age': 'Возраст от 16 лет',
    'participants.req_presence': 'Физическое присутствие все 2 дня',
    'participants.req_team': 'Команды до 3 человек',
    'participants.req_open': 'Открыто для всех национальностей',

    // Evaluation Criteria
    'criteria.title': 'Критерии оценки',
    'criteria.subtitle': 'Четыре ключевых аспекта, по которым жюри будет оценивать проекты',
    'criteria.business_potential': 'Бизнес-потенциал',
    'criteria.business_desc': 'Размер рынка, потенциал монетизации, решение реальной проблемы',
    'criteria.business_item1': 'Размер рынка и потенциал монетизации',
    'criteria.business_item2': 'Решение реальной проблемы',
    'criteria.business_item3': 'Уникальность подхода',
    'criteria.technical_implementation': 'Техническая реализация',
    'criteria.technical_desc': 'Качество использования AI-инструментов, функциональность прототипа',
    'criteria.technical_item1': 'Качество использования AI-инструментов',
    'criteria.technical_item2': 'Функциональность прототипа',
    'criteria.technical_item3': 'Техническая сложность',
    'criteria.user_experience': 'Пользовательский опыт',
    'criteria.ux_desc': 'Удобство использования, дизайн интерфейса, качество UX',
    'criteria.ux_item1': 'Удобство использования',
    'criteria.ux_item2': 'Дизайн интерфейса',
    'criteria.ux_item3': 'Качество UX',
    'criteria.presentation': 'Качество презентации',
    'criteria.presentation_desc': 'Четкость подачи идеи, демонстрация продукта, ответы на вопросы',
    'criteria.presentation_item1': 'Четкость подачи идеи',
    'criteria.presentation_item2': 'Демонстрация продукта',
    'criteria.presentation_item3': 'Ответы на вопросы жюри',
    'criteria.fair_evaluation_title': 'Справедливое оценивание',
    'criteria.fair_evaluation_desc': 'Каждый критерий имеет равный вес в итоговой оценке. Жюри состоит из опытных предпринимателей, технических экспертов и инвесторов, которые обеспечат объективную и всестороннюю оценку всех проектов.',

    // Prizes Section
    'prizes.title': 'Призы и награды',
    'prizes.subtitle': 'Общий призовой фонд составляет $6,000, который будет распределен между лучшими командами',
    'prizes.first_place': '1 место',
    'prizes.first_description': 'Гранд-приз для лучшего проекта',
    'prizes.second_place': '2 место',
    'prizes.second_description': 'Отличная реализация идеи',
    'prizes.third_place': '3 место',
    'prizes.third_description': 'Перспективный проект',
    'prizes.additional_title': 'Дополнительные возможности',
    'prizes.mentorship': 'Менторство от экспертов',
    'prizes.mentorship_desc': 'Возможность получить консультации от ведущих специалистов индустрии',
    'prizes.networking': 'Нетворкинг',
    'prizes.networking_desc': 'Знакомство с единомышленниками и потенциальными партнерами',
    'prizes.investment': 'Возможности инвестиций',
    'prizes.investment_desc': 'Презентация проектов перед потенциальными инвесторами',
    'prizes.participation_title': 'Условия участия',
    'prizes.team_size': 'Команды до 3 человек',
    'prizes.team_size_desc': 'Максимальный размер команды для участия в хакатоне',
    'prizes.from_scratch': 'Проект с нуля',
    'prizes.from_scratch_desc': 'Все решения должны быть разработаны во время хакатона',
    'prizes.ai_tools': 'Использование AI-инструментов',
    'prizes.ai_tools_desc': 'Активное применение современных AI-технологий в разработке',
    'prizes.challenge_title': 'Готовы принять вызов?',
    'prizes.challenge_desc': 'Покажите свои навыки в области AI-разработки и получите шанс выиграть один из призов!',
    'prizes.register_now': 'Зарегистрироваться сейчас',
    'prizes.acceleration': 'Акселерационные программы',
    'prizes.acceleration_desc': 'Приглашения в ведущие акселераторы региона',
    'prizes.employment': 'Трудоустройство',
    'prizes.employment_desc': 'Предложения работы от компаний-партнеров',

    // About Section - Additional
    'about.innovation_card_title': 'Инновации',
    'about.innovation_card_text': 'Экспериментальные форматы и выход за привычные рамки',
    'about.ai_card_title': 'AI-технологии',
    'about.ai_card_text': 'Использование передовых инструментов искусственного интеллекта',
    'about.result_card_title': 'Результат',
    'about.result_card_text': 'Создание функциональных продуктов за ограниченное время',

    // Partners Section
    'partners.title': 'Партнеры и спонсоры',
    'partners.subtitle': 'Присоединяйтесь к первому VibeCode хакатону в Узбекистане и получите максимальную видимость среди инновационного сообщества региона',
    'partners.title_sponsor': 'TITLE SPONSOR',
    'partners.title_sponsor_desc': 'Максимальная видимость и эксклюзивность',
    'partners.title_sponsor_feature1': 'Название хакатона с упоминанием компании',
    'partners.title_sponsor_feature2': 'Логотип на всех материалах (самый крупный размер)',
    'partners.title_sponsor_feature3': 'Эксклюзивная брендированная зона на площадке',
    'partners.title_sponsor_feature4': 'Персональная презентация компании',
    'partners.title_sponsor_feature5': 'Воркшоп от экспертов компании',
    'partners.title_sponsor_feature6': 'Собственная номинация с призом $1,000',
    'partners.title_sponsor_feature7': '2 ментора от компании',
    'partners.gold_sponsor': 'GOLD SPONSOR',
    'partners.gold_sponsor_desc': 'Премиальное партнерство с отличной видимостью',
    'partners.gold_sponsor_feature1': 'Крупный логотип на всех материалах',
    'partners.gold_sponsor_feature2': 'Брендированная зона на площадке',
    'partners.gold_sponsor_feature3': 'Упоминание в открытии хакатона',
    'partners.gold_sponsor_feature4': 'Воркшоп или мастер-класс (30 минут)',
    'partners.gold_sponsor_feature5': '1 ментор от компании',
    'partners.gold_sponsor_feature6': 'Специальная номинация ($500)',
    'partners.silver_sponsor': 'SILVER SPONSOR',
    'partners.silver_sponsor_desc': 'Качественное партнерство с хорошим охватом',
    'partners.silver_sponsor_feature1': 'Логотип на основных материалах',
    'partners.silver_sponsor_feature2': 'Упоминание на церемониях',
    'partners.silver_sponsor_feature3': 'Небольшая брендированная зона',
    'partners.silver_sponsor_feature4': 'Lightning talk (15 минут)',
    'partners.silver_sponsor_feature5': 'Презентация продуктов/вакансий',
    'partners.tech_sponsor': 'TECH SPONSOR',
    'partners.tech_sponsor_desc': 'Для IT-компаний, предоставляющих инструменты',
    'partners.tech_sponsor_feature1': 'Промокоды/лицензии для участников',
    'partners.tech_sponsor_feature2': 'API доступы или сервисы',
    'partners.tech_sponsor_feature3': 'Техническая поддержка',
    'partners.tech_sponsor_feature4': 'Логотип в разделе Tech Partners',
    'partners.catering_sponsor': 'CATERING SPONSOR',
    'partners.catering_sponsor_desc': 'Обеспечение питания участников',
    'partners.catering_sponsor_feature1': 'Брендинг зоны питания',
    'partners.catering_sponsor_feature2': 'Упоминание при каждом приеме пищи',
    'partners.catering_sponsor_feature3': 'Благодарность от участников',
    'partners.media_sponsor': 'MEDIA SPONSOR',
    'partners.media_sponsor_desc': 'Освещение и PR-поддержка',
    'partners.media_sponsor_feature1': 'Освещение хакатона',
    'partners.media_sponsor_feature2': 'Создание контента',
    'partners.media_sponsor_feature3': 'Взаимное продвижение',
    'partners.custom_packages': 'КАСТОМНЫЕ ПАКЕТЫ',
    'partners.custom_packages_desc': 'Индивидуальные условия',
    'partners.custom_packages_feature1': 'Обсуждение под ваши потребности',
    'partners.custom_packages_feature2': 'Гибкий бюджет',
    'partners.custom_packages_feature3': 'Уникальные активации',
    'partners.ecosystem_partners': 'Партнеры экосистемы',
    'partners.become_partner': 'Станьте партнером VibeCode хакатона',
    'partners.partner_desc': 'Получите доступ к 150+ лучшим техническим специалистам и предпринимателям региона. Покажите свои продукты и найдите талантливые команды для будущего сотрудничества.',
    'partners.contact_us': 'Связаться с нами',
    'partners.download_presentation': 'Скачать презентацию'
  },

  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.program': 'Program',
    'nav.participants': 'Participants',
    'nav.criteria': 'Criteria',
    'nav.prizes': 'Prizes',
    'nav.partners': 'Partners',
    'header.participate': 'Participate',

    // Hero Content
    'hero.hackathon': 'Hackathon',
    'hero.location_year': 'Tashkent 2025',
    'hero.subtitle': 'First Vibe Coding hackathon in Uzbekistan',
    'hero.description': '2-day intensive hackathon for creating startups using AI tools',
    'hero.date': 'November 15-16, 2025',
    'hero.location': 'Tashkent, Uzbekistan',
    'hero.participants': '150 participants',
    'hero.prize': '$6000 prize pool',
    'hero.register': 'Register',
    'hero.learn_more': 'Learn More',

    // Hackathon Details
    'details.what_is_vibe': 'What is Vibe Coding?',
    'details.vibe_description': 'Vibe Coding is a revolutionary approach to development where participants create functional applications and startups using next-generation AI tools.',
    'details.mission': 'Hackathon Mission:',
    'details.mission_text': 'We at Angel Connect believe that development and the approach to creating IT products is the area where the most global changes are happening right now. The mission of our VibeCode hackathon is to prove that small teams focused on creating products with AI can achieve fantastic results today.',
    'details.slogan': 'The future is here',

    // About Section
    'about.title': 'About Hackathon',
    'about.subtitle': 'Revolution in AI Development',
    'about.innovation_title': 'Innovative Format',
    'about.innovation_text': 'First hackathon in the region entirely dedicated to development using next-generation AI tools',
    'about.community_title': 'Strong Community',
    'about.community_text': '150+ participants from the best IT companies, startups and universities in Uzbekistan',
    'about.networking_title': 'Premium Networking',
    'about.networking_text': 'Unique opportunity to meet leading experts, investors and entrepreneurs of the region',
    'about.prizes_title': 'Serious Prizes',
    'about.prizes_text': '$6000 prize pool, mentorship from experts and opportunities for further project development',

    // Hackathon Program
    'program.title': 'Hackathon Program',
    'program.subtitle': 'Intensive 2-day innovation marathon',
    'program.day1': 'Day 1 - Start and Development',
    'program.day1_date': 'Saturday, November 15',
    'program.day2': 'Day 2 - Finals and Presentations',
    'program.day2_date': 'Sunday, November 16',
    'program.registration': 'Registration',
    'program.opening': 'Opening ceremony',
    'program.idea_pitches': 'Idea pitches (60 seconds per idea)',
    'program.team_formation': 'Team formation',
    'program.lunch': 'Lunch',
    'program.development_start': 'Development start',
    'program.workshop': 'Workshop "Agent Programming"',
    'program.mentoring': 'Mentoring sessions',
    'program.dinner': 'Dinner',
    'program.evening_workshops': 'Evening workshops on Vibe Coding tools',
    'program.night_dev': 'Night development (optional)',
    'program.breakfast': 'Breakfast',
    'program.final_dev': 'Final project development',
    'program.stop_dev': 'Development stop',
    'program.presentation_prep': 'Presentation preparation',
    'program.final_pitches': 'Final pitches (3 minutes + 2 minutes Q&A)',
    'program.jury_evaluation': 'Jury evaluation',
    'program.results': 'Results announcement and awards',
    'program.networking_closing': 'Networking and closing',

    // Participants Section
    'participants.title': 'Who Can Participate',
    'participants.subtitle': 'Hackathon is open to all professionals ready to experiment with AI tools',
    'participants.vibe_coders': 'Vibe Coders',
    'participants.vibe_coders_subtitle': 'main category',
    'participants.vibe_coders_desc': 'AI-tools enthusiasts',
    'participants.vibe_coders_item1': 'AI-tools enthusiasts',
    'participants.vibe_coders_item2': 'Product managers',
    'participants.vibe_coders_item3': 'Tech-minded entrepreneurs',
    'participants.vibe_coders_item4': 'Marketers wanting to create MVPs',
    'participants.designers': 'Designers',
    'participants.designers_subtitle': 'creative professionals',
    'participants.designers_desc': 'UX/UI and product designers',
    'participants.designers_item1': 'UX/UI designers',
    'participants.designers_item2': 'Product designers',
    'participants.designers_item3': 'User experience specialists',
    'participants.developers': 'Developers',
    'participants.developers_subtitle': 'technical specialists',
    'participants.developers_desc': 'Frontend, Backend, Mobile, AI/ML',
    'participants.developers_item1': 'Frontend/Backend developers',
    'participants.developers_item2': 'Fullstack developers',
    'participants.developers_item3': 'Mobile developers',
    'participants.developers_item4': 'AI/ML engineers',
    'participants.business': 'Business Professionals',
    'participants.business_subtitle': 'entrepreneurial community',
    'participants.business_desc': 'Startup founders and analysts',
    'participants.business_item1': 'Startup founders',
    'participants.business_item2': 'Business analysts',
    'participants.business_item3': 'Venture analysts',
    'participants.business_item4': 'Industry experts',
    'participants.requirements_title': 'Participant Requirements',
    'participants.teams_title': 'Teams',
    'participants.projects_title': 'Projects',
    'participants.team_req1': 'Up to 3 participants per team',
    'participants.team_req2': 'Age 16+',
    'participants.team_req3': 'Physical presence for 2 days',
    'participants.project_req1': 'Active use of AI tools',
    'participants.project_req2': 'Build from scratch during hackathon',
    'participants.project_req3': 'Functional MVP by the end',
    'participants.req_age': 'Age 16+',
    'participants.req_presence': 'Physical presence for all 2 days',
    'participants.req_team': 'Teams up to 3 people',
    'participants.req_open': 'Open to all nationalities',

    // Evaluation Criteria
    'criteria.title': 'Evaluation Criteria',
    'criteria.subtitle': 'Four key aspects by which the jury will evaluate projects',
    'criteria.business_potential': 'Business Potential',
    'criteria.business_desc': 'Market size, monetization potential, solving real problems',
    'criteria.business_item1': 'Market size and monetization potential',
    'criteria.business_item2': 'Solving real problems',
    'criteria.business_item3': 'Uniqueness of approach',
    'criteria.technical_implementation': 'Technical Implementation',
    'criteria.technical_desc': 'Quality of AI tools usage, prototype functionality',
    'criteria.technical_item1': 'Quality of AI tools usage',
    'criteria.technical_item2': 'Prototype functionality',
    'criteria.technical_item3': 'Technical complexity',
    'criteria.user_experience': 'User Experience',
    'criteria.ux_desc': 'Ease of use, interface design, UX quality',
    'criteria.ux_item1': 'Ease of use',
    'criteria.ux_item2': 'Interface design',
    'criteria.ux_item3': 'UX quality',
    'criteria.presentation': 'Presentation Quality',
    'criteria.presentation_desc': 'Clarity of idea presentation, product demo, Q&A responses',
    'criteria.presentation_item1': 'Clarity of idea presentation',
    'criteria.presentation_item2': 'Product demonstration',
    'criteria.presentation_item3': 'Answers to jury questions',
    'criteria.fair_evaluation_title': 'Fair Evaluation',
    'criteria.fair_evaluation_desc': 'Each criterion has equal weight in the final assessment. The jury consists of experienced entrepreneurs, technical experts and investors who will ensure objective and comprehensive evaluation of all projects.',

    // Prizes Section
    'prizes.title': 'Prizes and Awards',
    'prizes.subtitle': 'Total prize pool is $6,000, which will be distributed among the best teams',
    'prizes.first_place': '1st Place',
    'prizes.first_description': 'Grand prize for the best project',
    'prizes.second_place': '2nd Place',
    'prizes.second_description': 'Excellent idea implementation',
    'prizes.third_place': '3rd Place',
    'prizes.third_description': 'Promising project',
    'prizes.additional_title': 'Additional Opportunities',
    'prizes.mentorship': 'Expert Mentorship',
    'prizes.mentorship_desc': 'Opportunity to get consultations from leading industry specialists',
    'prizes.networking': 'Networking',
    'prizes.networking_desc': 'Meeting like-minded people and potential partners',
    'prizes.investment': 'Investment Opportunities',
    'prizes.investment_desc': 'Project presentations to potential investors',
    'prizes.participation_title': 'Participation Terms',
    'prizes.team_size': 'Teams up to 3 people',
    'prizes.team_size_desc': 'Maximum team size for hackathon participation',
    'prizes.from_scratch': 'Project from scratch',
    'prizes.from_scratch_desc': 'All solutions must be developed during the hackathon',
    'prizes.ai_tools': 'Use of AI tools',
    'prizes.ai_tools_desc': 'Active application of modern AI technologies in development',
    'prizes.challenge_title': 'Ready to take the challenge?',
    'prizes.challenge_desc': 'Show your AI development skills and get a chance to win one of the prizes!',
    'prizes.register_now': 'Register Now',
    'prizes.acceleration': 'Acceleration Programs',
    'prizes.acceleration_desc': 'Invitations to leading regional accelerators',
    'prizes.employment': 'Employment',
    'prizes.employment_desc': 'Job offers from partner companies',

    // About Section - Additional
    'about.innovation_card_title': 'Innovation',
    'about.innovation_card_text': 'Experimental formats and breaking beyond conventional boundaries',
    'about.ai_card_title': 'AI Technologies',
    'about.ai_card_text': 'Using cutting-edge artificial intelligence tools',
    'about.result_card_title': 'Results',
    'about.result_card_text': 'Creating functional products in limited time',

    // Partners Section
    'partners.title': 'Partners and Sponsors',
    'partners.subtitle': 'Join the first VibeCode hackathon in Uzbekistan and get maximum visibility among the region\'s innovation community',
    'partners.title_sponsor': 'TITLE SPONSOR',
    'partners.title_sponsor_desc': 'Maximum visibility and exclusivity',
    'partners.title_sponsor_feature1': 'Hackathon name with company mention',
    'partners.title_sponsor_feature2': 'Logo on all materials (largest size)',
    'partners.title_sponsor_feature3': 'Exclusive branded zone at venue',
    'partners.title_sponsor_feature4': 'Personal company presentation',
    'partners.title_sponsor_feature5': 'Workshop by company experts',
    'partners.title_sponsor_feature6': 'Own nomination with $1,000 prize',
    'partners.title_sponsor_feature7': '2 mentors from company',
    'partners.gold_sponsor': 'GOLD SPONSOR',
    'partners.gold_sponsor_desc': 'Premium partnership with excellent visibility',
    'partners.gold_sponsor_feature1': 'Large logo on all materials',
    'partners.gold_sponsor_feature2': 'Branded zone at venue',
    'partners.gold_sponsor_feature3': 'Mention at hackathon opening',
    'partners.gold_sponsor_feature4': 'Workshop or masterclass (30 minutes)',
    'partners.gold_sponsor_feature5': '1 mentor from company',
    'partners.gold_sponsor_feature6': 'Special nomination ($500)',
    'partners.silver_sponsor': 'SILVER SPONSOR',
    'partners.silver_sponsor_desc': 'Quality partnership with good reach',
    'partners.silver_sponsor_feature1': 'Logo on main materials',
    'partners.silver_sponsor_feature2': 'Mention at ceremonies',
    'partners.silver_sponsor_feature3': 'Small branded zone',
    'partners.silver_sponsor_feature4': 'Lightning talk (15 minutes)',
    'partners.silver_sponsor_feature5': 'Product/job presentation',
    'partners.tech_sponsor': 'TECH SPONSOR',
    'partners.tech_sponsor_desc': 'For IT companies providing tools',
    'partners.tech_sponsor_feature1': 'Promo codes/licenses for participants',
    'partners.tech_sponsor_feature2': 'API access or services',
    'partners.tech_sponsor_feature3': 'Technical support',
    'partners.tech_sponsor_feature4': 'Logo in Tech Partners section',
    'partners.catering_sponsor': 'CATERING SPONSOR',
    'partners.catering_sponsor_desc': 'Providing participant catering',
    'partners.catering_sponsor_feature1': 'Catering area branding',
    'partners.catering_sponsor_feature2': 'Mention at every meal',
    'partners.catering_sponsor_feature3': 'Gratitude from participants',
    'partners.media_sponsor': 'MEDIA SPONSOR',
    'partners.media_sponsor_desc': 'Coverage and PR support',
    'partners.media_sponsor_feature1': 'Hackathon coverage',
    'partners.media_sponsor_feature2': 'Content creation',
    'partners.media_sponsor_feature3': 'Mutual promotion',
    'partners.custom_packages': 'CUSTOM PACKAGES',
    'partners.custom_packages_desc': 'Individual terms',
    'partners.custom_packages_feature1': 'Discussion tailored to your needs',
    'partners.custom_packages_feature2': 'Flexible budget',
    'partners.custom_packages_feature3': 'Unique activations',
    'partners.ecosystem_partners': 'Ecosystem Partners',
    'partners.become_partner': 'Become a VibeCode hackathon partner',
    'partners.partner_desc': 'Get access to 150+ best technical specialists and entrepreneurs in the region. Showcase your products and find talented teams for future collaboration.',
    'partners.contact_us': 'Contact Us',
    'partners.download_presentation': 'Download Presentation'
  },

  uz: {
    // Header
    'nav.home': 'Bosh sahifa',
    'nav.about': 'Haqida',
    'nav.program': 'Dastur',
    'nav.participants': 'Ishtirokchilar',
    'nav.criteria': 'Mezonlar',
    'nav.prizes': 'Mukofotlar',
    'nav.partners': 'Hamkorlar',
    'header.participate': 'Ishtirok etish',

    // Hero Content
    'hero.hackathon': 'Hakaton',
    'hero.location_year': 'Toshkent 2025',
    'hero.subtitle': 'O\'zbekistondagi birinchi Vibe Coding hakaton',
    'hero.description': 'AI vositalar yordamida startaplar yaratish uchun 2 kunlik intensiv hakaton',
    'hero.date': '15-16 noyabr, 2025',
    'hero.location': 'Toshkent, O\'zbekiston',
    'hero.participants': '150 ishtirokchi',
    'hero.prize': '$6000 mukofot fondi',
    'hero.register': 'Ro\'yxatdan o\'tish',
    'hero.learn_more': 'Batafsil',

    // Hackathon Details
    'details.what_is_vibe': 'Vibe Coding nima?',
    'details.vibe_description': 'Vibe Coding - bu ishtirokchilar yangi avlod AI vositalari yordamida funksional ilovalar va startaplar yaratadigan inqilobiy ishlab chiqish yondashuvi.',
    'details.mission': 'Hakaton missiyasi:',
    'details.mission_text': 'Biz Angel Connect\'da ishlab chiqish va IT mahsulotlarini yaratish bugungi kunda eng tez rivojlanayotgan va o\'zgarayotgan soha ekaniga ishonamiz. VibeCode hakatonining missiyasi — AI yordamida mahsulot yaratayotgan kichik jamoalar ham bugun katta natijalarga erisha olishini ko\'rsatish.',
    'details.slogan': 'Kelajak allaqachon shu yerda',

    // About Section
    'about.title': 'Hakaton haqida',
    'about.subtitle': 'AI ishlab chiqishda inqilob',
    'about.innovation_title': 'Innovatsion format',
    'about.innovation_text': 'Mintaqadagi yangi avlod AI vositalaridan foydalanishga to\'liq bag\'ishlangan birinchi hakaton',
    'about.community_title': 'Kuchli hamjamiyat',
    'about.community_text': 'O\'zbekistonning eng yaxshi IT kompaniyalari, startaplari va universitetlaridan 150+ ishtirokchi',
    'about.networking_title': 'Premium tarmoqsozlik',
    'about.networking_text': 'Mintaqaning yetakchi ekspertlari, investorlari va tadbirkorlari bilan tanishishning noyob imkoniyati',
    'about.prizes_title': 'Jiddiy mukofotlar',
    'about.prizes_text': '$6000 mukofot fondi, ekspertlardan mentolik va loyihalarni yanada rivojlantirish imkoniyatlari',

    // Hackathon Program
    'program.title': 'Hakaton dasturi',
    'program.subtitle': 'Intensiv 2 kunlik innovatsiya marafoni',
    'program.day1': '1-kun - Start va dasturlash',
    'program.day1_date': 'Shanba, 15 noyabr',
    'program.day2': '2-kun - Final va taqdimotlar',
    'program.day2_date': 'Yakshanba, 16 noyabr',
    'program.registration': 'Ro\'yxatdan o\'tish',
    'program.opening': 'Tantanali ochilish',
    'program.idea_pitches': 'G\'oya pitchlari (har bir g\'oya uchun 60 soniya)',
    'program.team_formation': 'Jamoa tuzish',
    'program.lunch': 'Tushlik',
    'program.development_start': 'Dasturlashni boshlash',
    'program.workshop': 'Vorkshop "Agent dasturlash"',
    'program.mentoring': 'Mentor sessiyalari',
    'program.dinner': 'Kechki ovqat',
    'program.evening_workshops': 'Vibe Coding vositalari bo\'yicha kechki vorkshoplar',
    'program.night_dev': 'Tungi dasturlash (ixtiyoriy)',
    'program.breakfast': 'Nonushta',
    'program.final_dev': 'Yakuniy dasturlash ishlari',
    'program.stop_dev': 'Dasturlashni to\'xtatish',
    'program.presentation_prep': 'Taqdimotga tayyorgarlik',
    'program.final_pitches': 'Yakuniy pitchlar (3 daqiqa + 2 daqiqa Q&A)',
    'program.jury_evaluation': 'Hakamlar hay\'ati baholashi',
    'program.results': 'Natijalarni e\'lon qilish va mukofotlash',
    'program.networking_closing': 'Netvorking va yopilish',

    // Participants Section
    'participants.title': 'Kim ishtirok etishi mumkin',
    'participants.subtitle': 'Hakaton AI vositalari bilan tajriba o\'tkazishga tayyor barcha mutaxassislarga ochiq',
    'participants.vibe_coders': 'Vibe Coders',
    'participants.vibe_coders_subtitle': 'asosiy kategoriya',
    'participants.vibe_coders_desc': 'AI vositalari ixlosmandlari',
    'participants.vibe_coders_item1': 'AI vositalari ixlosmandlari',
    'participants.vibe_coders_item2': 'Mahsulot menejerlari',
    'participants.vibe_coders_item3': 'Texnik fikrlash qobiliyatiga ega tadbirkorlar',
    'participants.vibe_coders_item4': 'MVP yaratmoqchi bo\'lgan marketologlar',
    'participants.designers': 'Dizaynerlar',
    'participants.designers_subtitle': 'ijodiy mutaxassislar',
    'participants.designers_desc': 'UX/UI va mahsulot dizaynerlari',
    'participants.designers_item1': 'UX/UI dizaynerlar',
    'participants.designers_item2': 'Mahsulot dizaynerlari',
    'participants.designers_item3': 'Foydalanuvchi tajribasi mutaxassislari',
    'participants.developers': 'Dasturchilar',
    'participants.developers_subtitle': 'texnik mutaxassislar',
    'participants.developers_desc': 'Frontend, Backend, Mobile, AI/ML',
    'participants.developers_item1': 'Frontend/Backend dasturchilar',
    'participants.developers_item2': 'Fullstack dasturchilar',
    'participants.developers_item3': 'Mobile dasturchilar',
    'participants.developers_item4': 'AI/ML muhandislar',
    'participants.business': 'Biznes mutaxassislari',
    'participants.business_subtitle': 'tadbirkorlik hamjamiyati',
    'participants.business_desc': 'Startap asoschilari va analitiklar',
    'participants.business_item1': 'Startap asoschilari',
    'participants.business_item2': 'Biznes analitiklar',
    'participants.business_item3': 'Venchur analitiklar',
    'participants.business_item4': 'Soha ekspertlari',
    'participants.requirements_title': 'Ishtirokchilarga qo\'yiladigan talablar',
    'participants.teams_title': 'Jamoalar',
    'participants.projects_title': 'Loyihalar',
    'participants.team_req1': 'Jamoa uchun 3 kishigacha',
    'participants.team_req2': '16 yoshdan yuqori',
    'participants.team_req3': '2 kun jismoniy ishtirok',
    'participants.project_req1': 'AI vositalardan faol foydalanish',
    'participants.project_req2': 'Hakaton davomida noldan ishlab chiqish',
    'participants.project_req3': 'Oxirigacha funksional MVP',
    'participants.req_age': '16 yoshdan yuqori',
    'participants.req_presence': 'Barcha 2 kun jismoniy ishtirok',
    'participants.req_team': '3 kishigacha jamoalar',
    'participants.req_open': 'Barcha millatlarga ochiq',

    // Evaluation Criteria
    'criteria.title': 'Baholash mezonlari',
    'criteria.subtitle': 'Hakamlar hay\'ati loyihalarni baholaydigan to\'rtta asosiy jihat',
    'criteria.business_potential': 'Biznes salohiyati',
    'criteria.business_desc': 'Bozor hajmi, monetizatsiya salohiyati, haqiqiy muammolarni hal qilish',
    'criteria.business_item1': 'Bozor hajmi va monetizatsiya salohiyati',
    'criteria.business_item2': 'Haqiqiy muammolarni hal qilish',
    'criteria.business_item3': 'Yondashuvning noyobligi',
    'criteria.technical_implementation': 'Texnik amalga oshirish',
    'criteria.technical_desc': 'AI vositalardan foydalanish sifati, prototip funksionalligi',
    'criteria.technical_item1': 'AI vositalardan foydalanish sifati',
    'criteria.technical_item2': 'Prototip funksionalligi',
    'criteria.technical_item3': 'Texnik murakkablik',
    'criteria.user_experience': 'Foydalanuvchi tajribasi',
    'criteria.ux_desc': 'Foydalanish qulayligi, interfeys dizayni, UX sifati',
    'criteria.ux_item1': 'Foydalanish qulayligi',
    'criteria.ux_item2': 'Interfeys dizayni',
    'criteria.ux_item3': 'UX sifati',
    'criteria.presentation': 'Taqdimot sifati',
    'criteria.presentation_desc': 'G\'oyani taqdim etish aniqligi, mahsulot namoyishi, savollarga javoblar',
    'criteria.presentation_item1': 'G\'oyani taqdim etish aniqligi',
    'criteria.presentation_item2': 'Mahsulot namoyishi',
    'criteria.presentation_item3': 'Hakamlar savollariga javoblar',
    'criteria.fair_evaluation_title': 'Adolatli baholash',
    'criteria.fair_evaluation_desc': 'Har bir mezon yakuniy natijada teng ahamiyatga ega. Hakamlar hay\'ati tajribali tadbirkorlar, texnik mutaxassislar va investorlardan iborat bo\'lib, ular barcha loyihalarni xolis va har tomonlama baholashni ta\'minlaydi.',

    // Prizes Section
    'prizes.title': 'Mukofotlar va sovrinlar',
    'prizes.subtitle': 'Umumiy mukofot fondi $6,000 ni tashkil etadi va eng yaxshi jamoalar o\'rtasida taqsimlanadi',
    'prizes.first_place': '1-o\'rin',
    'prizes.first_description': 'Eng yaxshi loyiha uchun bosh mukofot',
    'prizes.second_place': '2-o\'rin',
    'prizes.second_description': 'G\'oyaning ajoyib amalga oshirilishi',
    'prizes.third_place': '3-o\'rin',
    'prizes.third_description': 'Istiqbolli loyiha',
    'prizes.additional_title': 'Qo\'shimcha imkoniyatlar',
    'prizes.mentorship': 'Ekspert mentorligi',
    'prizes.mentorship_desc': 'Sohaning yetakchi mutaxassislaridan maslahat olish imkoniyati',
    'prizes.networking': 'Tarmoqsozlik',
    'prizes.networking_desc': 'Hamfikr odamlar va potentsial hamkorlar bilan tanishish',
    'prizes.investment': 'Investitsiya imkoniyatlari',
    'prizes.investment_desc': 'Loyihalarni potentsial investorlarga taqdim etish',
    'prizes.participation_title': 'Ishtirok etish shartlari',
    'prizes.team_size': '3 kishigacha jamoalar',
    'prizes.team_size_desc': 'Jamoada maksimal 3 kishi ishtirok etishi mumkin',
    'prizes.from_scratch': 'Noldan loyiha',
    'prizes.from_scratch_desc': 'Barcha yechimlar hakaton davomida ishlab chiqilishi kerak',
    'prizes.ai_tools': 'AI vositalardan foydalanish',
    'prizes.ai_tools_desc': 'Ishlab chiqishda zamonaviy AI texnologiyalarining faol qo\'llanilishi',
    'prizes.challenge_title': 'Sinovga tayyormisiz?',
    'prizes.challenge_desc': 'AI ishlab chiqish ko\'nikmalaringizni ko\'rsating va mukofotlardan birini yutish imkoniyatiga ega bo\'ling!',
    'prizes.register_now': 'Hoziroq ro\'yxatdan o\'ting',
    'prizes.acceleration': 'Akseleratsiya dasturlari',
    'prizes.acceleration_desc': 'Mintaqaning yetakchi akseleratorlariga takliflar',
    'prizes.employment': 'Ish bilan ta\'minlash',
    'prizes.employment_desc': 'Hamkor kompaniyalardan ish takliflari',

    // About Section - Additional
    'about.innovation_card_title': 'Innovatsiya',
    'about.innovation_card_text': 'Eksperimental formatlar va an\'anaviy chegaralardan chiqish',
    'about.ai_card_title': 'AI texnologiyalari',
    'about.ai_card_text': 'Sun\'iy intellektning ilg\'or vositalaridan foydalanish',
    'about.result_card_title': 'Natija',
    'about.result_card_text': 'Cheklangan vaqtda funksional mahsulotlar yaratish',

    // Partners Section
    'partners.title': 'Hamkorlar va homiylar',
    'partners.subtitle': 'O\'zbekistondagi birinchi VibeCode hakatonga qo\'shiling va mintaqaning innovatsion hamjamiyati orasida maksimal ko\'rinishga ega bo\'ling',
    'partners.title_sponsor': 'BOSH HOMIY',
    'partners.title_sponsor_desc': 'Maksimal ko\'rinish va eksklyuzivlik',
    'partners.title_sponsor_feature1': 'Kompaniya nomi bilan hakaton nomi',
    'partners.title_sponsor_feature2': 'Barcha materiallarda logo (eng katta o\'lcham)',
    'partners.title_sponsor_feature3': 'Maydonda eksklyuziv brendlangan zona',
    'partners.title_sponsor_feature4': 'Kompaniyaning shaxsiy taqdimoti',
    'partners.title_sponsor_feature5': 'Kompaniya ekspertlari tomonidan vorkshop',
    'partners.title_sponsor_feature6': '$1,000 mukofot bilan o\'z nominatsiyasi',
    'partners.title_sponsor_feature7': 'Kompaniyadan 2 mentor',
    'partners.gold_sponsor': 'OLTIN HOMIY',
    'partners.gold_sponsor_desc': 'Ajoyib ko\'rinish bilan premium hamkorlik',
    'partners.gold_sponsor_feature1': 'Barcha materiallarda katta logo',
    'partners.gold_sponsor_feature2': 'Maydonda brendlangan zona',
    'partners.gold_sponsor_feature3': 'Hakaton ochilishida eslatib o\'tish',
    'partners.gold_sponsor_feature4': 'Vorkshop yoki master-klass (30 daqiqa)',
    'partners.gold_sponsor_feature5': 'Kompaniyadan 1 mentor',
    'partners.gold_sponsor_feature6': 'Maxsus nominatsiya ($500)',
    'partners.silver_sponsor': 'KUMUSH HOMIY',
    'partners.silver_sponsor_desc': 'Yaxshi qamrov bilan sifatli hamkorlik',
    'partners.silver_sponsor_feature1': 'Asosiy materiallarda logo',
    'partners.silver_sponsor_feature2': 'Marosimlarda eslatib o\'tish',
    'partners.silver_sponsor_feature3': 'Kichik brendlangan zona',
    'partners.silver_sponsor_feature4': 'Lightning talk (15 daqiqa)',
    'partners.silver_sponsor_feature5': 'Mahsulot/ish taqdimoti',
    'partners.tech_sponsor': 'TEXNIK HOMIY',
    'partners.tech_sponsor_desc': 'Vositalar taqdim etuvchi IT kompaniyalar uchun',
    'partners.tech_sponsor_feature1': 'Ishtirokchilar uchun promo kodlar/litsenziyalar',
    'partners.tech_sponsor_feature2': 'API kirish yoki xizmatlar',
    'partners.tech_sponsor_feature3': 'Texnik qo\'llab-quvvatlash',
    'partners.tech_sponsor_feature4': 'Tech Partners bo\'limida logo',
    'partners.catering_sponsor': 'CATERING SPONSOR',
    'partners.catering_sponsor_desc': 'Ishtirokchilarni ovqat bilan ta\'minlash',
    'partners.catering_sponsor_feature1': 'Ovqatlanish zonasida brending',
    'partners.catering_sponsor_feature2': 'Har bir ovqat paytida eslatib o\'tiladi',
    'partners.catering_sponsor_feature3': 'Ishtirokchilarning minnatdorchiligi',
    'partners.media_sponsor': 'MEDIA SPONSOR',
    'partners.media_sponsor_desc': 'Yoritish va PR-qo\'llab-quvvatlash',
    'partners.media_sponsor_feature1': 'Hakatonni yoritish',
    'partners.media_sponsor_feature2': 'Kontent yaratish',
    'partners.media_sponsor_feature3': 'O\'zaro targ\'ibot',
    'partners.custom_packages': 'CUSTOM PAKETLAR',
    'partners.custom_packages_desc': 'Individual shartlar',
    'partners.custom_packages_feature1': 'Sizning ehtiyojlaringizga moslashuv',
    'partners.custom_packages_feature2': 'Moslashuvchan byudje',
    'partners.custom_packages_feature3': '',
    'partners.ecosystem_partners': 'Ekotizim hamkorlari',
    'partners.become_partner': 'VibeCode hakaton hamkori bo\'ling',
    'partners.partner_desc': 'Mintaqaning 150+ eng yaxshi texnik mutaxassislari va tadbirkorlariga kirish oling. Mahsulotlaringizni ko\'rsating va kelajakdagi hamkorlik uchun iqtidorli jamoalarni toping.',
    'partners.contact_us': 'Biz bilan bog\'laning',
    'partners.download_presentation': 'Taqdimotni yuklab olish'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}